export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const LOAD_MYIMAGES_SUCCESS = "LOAD_MYIMAGES_SUCCESS";
export const LOAD_MYCOURSES_SUCCESS = "LOAD_MYCOURSES_SUCCESS";
export const LOAD_MYROUTES_SUCCESS = "LOAD_MYROUTES_SUCCESS";

export const SELECTED_BACKGROUND_IMAGE = "SELECTED_BACKGROUND_IMAGE";

export const LOAD_BACKGROUND_IMAGE_SUCCESS = "LOAD_BACKGROUND_IMAGE_SUCCESS";
export const CHANGE_COURSE_NAME = "CHANGE_COURSE_NAME";
export const CHANGE_CIRCLE_STYLE = "CHANGE_CIRCLE_STYLE";
export const SAVE_COURSE = "SAVE_COURSE";