export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const LOAD_MYIMAGES_SUCCESS = "LOAD_MYIMAGES_SUCCESS";
export const LOAD_MYCOURSES_SUCCESS = "LOAD_MYCOURSES_SUCCESS";

export const SELECTED_BACKGROUND_IMAGE = "SELECTED_BACKGROUND_IMAGE";
export const CHANGE_CIRCLE_STYLE = "CHANGE_CIRCLE_STYLE";