export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const START_LOADING = "START_LOADING";
export const LOAD_IMAGES_SUCCESS = "LOAD_IMAGES_SUCCESS";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_ROUTES_SUCCESS = "LOAD_ROUTES_SUCCESS";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";

export const SELECTED_BACKGROUND_IMAGE = "SELECTED_BACKGROUND_IMAGE";

export const LOAD_BACKGROUND_IMAGE_SUCCESS = "LOAD_BACKGROUND_IMAGE_SUCCESS";
export const CHANGE_COURSE_NAME = "CHANGE_COURSE_NAME";
export const CHANGE_CIRCLE_STYLE = "CHANGE_CIRCLE_STYLE";
export const SAVE_COURSE = "SAVE_COURSE";